# Generated by Django 5.2.14 on 2026-07-10 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_enrollment_deadline_alter_upload_file"),
        ("problems", "0003_alter_problemcomment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="author",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="출제자",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="category",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="course.coursecategory",
                verbose_name="분야",
            ),
        ),
        migrations.AlterField(
            model_name="problemcomment",
            name="author",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solverecord",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="solve_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
