# Generated by Django 5.2.14 on 2026-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schedule_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
    ]
