# Generated by Django 5.2.14 on 2026-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='recurrence_group',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='반복 그룹 UUID'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', '반복 안함'), ('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월'), ('YEARLY', '매년')], default='NONE', max_length=10, verbose_name='반복 유형'),
        ),
    ]
