# Generated by Django 5.2.14 on 2026-07-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_schedule_recurrence_group_schedule_recurrence_type"),
        ("problems", "0003_alter_problemcomment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="activity_logs",
                to="problems.problem",
            ),
        ),
    ]
