# Generated by Django 5.2.14 on 2026-07-09 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="자료명")),
                (
                    "file",
                    models.FileField(
                        help_text="허용 확장자: pdf, doc, docx, ppt, pptx (최대 20MB)",
                        upload_to="personal_docs/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "ppt", "pptx"]
                            )
                        ],
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        verbose_name="추출된 본문 (미리보기·문제생성에 사용)",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("ox", "OX"),
                            ("short", "단답형"),
                            ("essay", "서술형"),
                        ],
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer", models.TextField(verbose_name="정답/모범답안")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mypage.personaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
