# Generated by Django 5.2.14 on 2026-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0002_personalfolder_personaldocument_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldocument",
            name="summary",
            field=models.TextField(blank=True, verbose_name="AI 자동 요약"),
        ),
    ]
