# Generated by Django 5.2.14 on 2026-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0003_personaldocument_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="feedback",
            field=models.TextField(
                blank=True, verbose_name="LLM 채점 피드백 (단답/서술형만)"
            ),
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="is_correct",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="채점 결과 (미응답 시 None)",
            ),
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="user_answer",
            field=models.TextField(blank=True, verbose_name="사용자가 제출한 답"),
        ),
    ]
