# Generated by Django 5.2.14 on 2026-07-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0004_generatedquestion_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("processing", "처리중"),
                    ("done", "완료"),
                    ("failed", "실패"),
                ],
                default="done",
                max_length=10,
                verbose_name="문제 생성 상태 (백그라운드 처리 추적용)",
            ),
        ),
        migrations.AddField(
            model_name="personaldocument",
            name="summary_status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("processing", "처리중"),
                    ("done", "완료"),
                    ("failed", "실패"),
                ],
                default="done",
                max_length=10,
                verbose_name="요약 생성 상태 (백그라운드 처리 추적용)",
            ),
        ),
        migrations.AlterField(
            model_name="generatedquestion",
            name="answer",
            field=models.TextField(blank=True, verbose_name="정답/모범답안"),
        ),
        migrations.AlterField(
            model_name="generatedquestion",
            name="question_text",
            field=models.TextField(blank=True),
        ),
    ]
