# Generated by Django 5.2.14 on 2026-07-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0005_generatedquestion_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldocument",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                verbose_name="삭제됨 (사용자 화면에서만 숨김, 강의 생성용으로 보존)",
            ),
        ),
        migrations.AddField(
            model_name="personaldocument",
            name="subject_code",
            field=models.CharField(
                blank=True,
                help_text="같은 과목 코드로 자료가 쌓이면 강의가 자동 생성됩니다.",
                max_length=50,
                verbose_name="과목 코드",
            ),
        ),
    ]
