# Generated by Django 5.2.14 on 2026-07-10 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0006_personaldocument_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldocument",
            name="file",
            field=models.FileField(
                help_text="허용 확장자: pdf, doc, docx, ppt, pptx, txt, md, rtf, hwp, hwpx, jpg, jpeg, png (최대 20MB)",
                upload_to="personal_docs/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "doc",
                            "docx",
                            "ppt",
                            "pptx",
                            "txt",
                            "md",
                            "rtf",
                            "hwp",
                            "hwpx",
                            "jpg",
                            "jpeg",
                            "png",
                        ]
                    )
                ],
            ),
        ),
    ]
