# Generated by Django 5.2.14 on 2026-07-10 08:34

from django.db import migrations, models

INITIAL_SUBJECTS = ["프로그래밍언어론", "운영체제", "소프트웨어공학"]


def seed_subjects(apps, schema_editor):
    Subject = apps.get_model("mypage", "Subject")
    Subject.objects.bulk_create(
        [Subject(name=name) for name in INITIAL_SUBJECTS], ignore_conflicts=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0007_alter_personaldocument_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="강의 이름"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_subjects, migrations.RunPython.noop),
    ]
