# Generated by Django 5.2.14 on 2026-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0008_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("assignment", "과제 (문제 제작용 데이터)"),
                    ("lecture", "일반 강의 자료"),
                ],
                default="assignment",
                help_text="과제(문제 제작용)만 자동 강의 생성 대상에 포함됩니다.",
                max_length=10,
                verbose_name="자료 구분",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="과목 코드"
            ),
        ),
    ]
