# Generated by Django 5.2.14 on 2026-05-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_poll_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 일시"),
        ),
    ]
