# Generated by Django 5.2.14 on 2026-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_survey_surveyquestion_surveyquestionchoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="question_description",
            field=models.TextField(blank=True, verbose_name="질문 설명"),
        ),
    ]
