# Generated by Django 5.2.14 on 2026-06-05 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_surveycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='모집 제목')),
                ('description', models.TextField(blank=True, verbose_name='모집 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 일시')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='마감 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('student_id', models.CharField(max_length=20, verbose_name='학번')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('motivation', models.TextField(verbose_name='지원 동기')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='제출 IP')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.recruitmentform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
