# Generated by Django 5.2.14 on 2026-06-15 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_recruitmentform_recruitmentapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='community.communitypost', verbose_name='게시글')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatheringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='모임 제목')),
                ('description', models.TextField(verbose_name='모임 상세 설명')),
                ('event_date', models.DateTimeField(verbose_name='모임 일시')),
                ('location', models.CharField(max_length=200, verbose_name='모임 장소')),
                ('max_participants', models.PositiveIntegerField(verbose_name='최대 정원')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='개설일시')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='취소 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatherings_created', to=settings.AUTH_USER_MODEL, verbose_name='개설자')),
                ('participants', models.ManyToManyField(blank=True, related_name='gathering_events', to=settings.AUTH_USER_MODEL, verbose_name='참여자 목록')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatheringComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_comments', to='community.gatheringevent', verbose_name='번개 모임')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
