# Generated by Django 5.2.14 on 2026-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_communitypostlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='공지사항 여부'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정 여부'),
        ),
        migrations.AddField(
            model_name='gatheringevent',
            name='category',
            field=models.CharField(choices=[('study', '스터디'), ('drink', '술')], default='study', max_length=10, verbose_name='모임 종류'),
        ),
    ]
