# Generated by Django 5.2.14 on 2026-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_gatheringleavelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('free', '자유게시판'), ('feedback', '피드백게시판')], default='free', max_length=20, verbose_name='게시판 분류'),
        ),
    ]
