# Generated by Django 5.2.14 on 2026-06-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_communitycomment_parent_gatheringcomment_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_attachments/%Y/%m/%d/', verbose_name='첨부파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.communitypost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 첨부파일',
                'verbose_name_plural': '게시글 첨부파일 목록',
            },
        ),
    ]
