# Generated by Django 5.2.14 on 2026-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_communitypostattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 게시'),
        ),
    ]
