# Generated by Django 5.2.14 on 2026-06-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_add_communitypost_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='community.communitypost', verbose_name='연관 게시글'),
        ),
    ]
