# Generated by Django 5.2.14 on 2026-06-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_survey_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('free', '자유게시판'), ('feedback', '피드백게시판'), ('academic', '학사일정')], default='free', max_length=20, verbose_name='게시판 분류'),
        ),
    ]
