# Generated by Django 5.2.14 on 2026-06-26 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0021_alter_communitypost_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="category",
            field=models.CharField(
                choices=[
                    ("free", "자유게시판"),
                    ("feedback", "피드백게시판"),
                    ("academic", "학사공지"),
                ],
                default="free",
                max_length=20,
                verbose_name="게시판 분류",
            ),
        ),
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=100, verbose_name="방명록 내용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestbook_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "방명록",
                "verbose_name_plural": "방명록 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
