# Generated by Django 5.2.14 on 2026-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0022_guestbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="category",
            field=models.CharField(
                choices=[
                    ("free", "자유게시판"),
                    ("feedback", "피드백게시판"),
                    ("academic", "학사공지"),
                    ("ai", "AI 게시판"),
                    ("algorithm", "알고리즘 게시판"),
                    ("hackathon", "해커톤 게시판"),
                ],
                default="free",
                max_length=20,
                verbose_name="게시판 분류",
            ),
        ),
    ]
