# Generated by Django 5.2.14 on 2026-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_student_number_to_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="동아리원 인증 여부"),
        ),
        migrations.AddField(
            model_name="student",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="재학증명서 또는 학생증 사진 (JPG, PNG, PDF)",
                null=True,
                upload_to="verification_docs/%y/%m/%d/",
                verbose_name="인증 서류",
            ),
        ),
    ]
