# Generated by Django 5.2.14 on 2026-06-14 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_lmstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaves',
            field=models.PositiveIntegerField(default=0, verbose_name='낙엽'),
        ),
        migrations.CreateModel(
            name='LeafTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='변동 수량')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='거래 유형')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='상세 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래 일시')),
                ('previous_hash', models.CharField(blank=True, max_length=64, verbose_name='이전 트랜잭션 해시')),
                ('hash', models.CharField(blank=True, max_length=64, verbose_name='현재 트랜잭션 해시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
