# Generated by Django 5.2.14 on 2026-06-14 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_leaves_leaftransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='보상 코드')),
                ('amount', models.PositiveIntegerField(verbose_name='지급 낙엽 수량')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '보상 코드',
                'verbose_name_plural': '보상 코드 목록',
            },
        ),
        migrations.CreateModel(
            name='LeafCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용 일시')),
                ('leaf_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.leafcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보상 코드 사용 이력',
                'verbose_name_plural': '보상 코드 사용 이력 목록',
                'unique_together': {('user', 'leaf_code')},
            },
        ),
    ]
