# Generated by Django 5.2.14 on 2026-06-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pushsubscription'),
        ('community', '0017_communitycomment_parent_gatheringcomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.communitypost', verbose_name='관련 게시글'),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_post_comment',
            field=models.BooleanField(default=True, verbose_name='내 게시글 댓글 및 답글 알림 받기'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('gathering_created', '새 번개 모임 개설'), ('gathering_join', '모임 참여 신청'), ('gathering_leave', '모임 참여 취소'), ('gathering_comment', '모임 댓글 등록'), ('gathering_update', '모임 정보 변경'), ('gathering_cancel', '모임 취소'), ('post_comment', '게시글 댓글 등록'), ('comment_reply', '댓글 답글 등록')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
