# Generated by Django 5.2.14 on 2026-06-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("gathering_created", "새 번개 모임 개설"),
                    ("gathering_join", "모임 참여 신청"),
                    ("gathering_leave", "모임 참여 취소"),
                    ("gathering_comment", "모임 댓글 등록"),
                    ("gathering_update", "모임 정보 변경"),
                    ("gathering_cancel", "모임 취소"),
                    ("post_comment", "게시글 댓글 등록"),
                    ("comment_reply", "댓글 답글 등록"),
                    ("game_season_ending", "게임 시즌 종료 예정"),
                    ("game_season_reward", "게임 시즌 보상 지급"),
                ],
                max_length=20,
                verbose_name="알림 유형",
            ),
        ),
    ]
