# Generated by Django 5.2.14 on 2026-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_game_season_notification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="notify_game_season_ending",
            field=models.BooleanField(
                default=True, verbose_name="게임 시즌 종료 알림 받기"
            ),
        ),
    ]
