# Generated by Django 5.2.14 on 2026-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_add_notify_game_season_ending"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False, verbose_name="AI 봇"),
        ),
    ]
