# Generated by Django 5.2.14 on 2026-10-02 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_is_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="이동 경로"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("gathering_created", "새 번개 모임 개설"),
                    ("gathering_join", "모임 참여 신청"),
                    ("gathering_leave", "모임 참여 취소"),
                    ("gathering_comment", "모임 댓글 등록"),
                    ("gathering_update", "모임 정보 변경"),
                    ("gathering_cancel", "모임 취소"),
                    ("post_comment", "게시글 댓글 등록"),
                    ("comment_reply", "댓글 답글 등록"),
                    ("game_season_ending", "게임 시즌 종료 예정"),
                    ("game_season_reward", "게임 시즌 보상 지급"),
                    ("friend_request", "친구 요청"),
                    ("friend_accept", "친구 요청 수락"),
                    ("game_invite", "게임 초대"),
                ],
                max_length=20,
                verbose_name="알림 유형",
            ),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "요청 중"), ("accepted", "친구")],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일시"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수락일시"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청한 사람",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청받은 사람",
                    ),
                ),
            ],
            options={
                "verbose_name": "친구 관계",
                "verbose_name_plural": "친구 관계 목록",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"), name="unique_friendship_pair"
                    )
                ],
            },
        ),
    ]
