# Generated by Django 5.2.14 on 2026-10-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="graduated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="졸업생 전환일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_graduate",
            field=models.BooleanField(default=False, verbose_name="졸업생"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("gathering_created", "새 번개 모임 개설"),
                    ("gathering_join", "모임 참여 신청"),
                    ("gathering_leave", "모임 참여 취소"),
                    ("gathering_comment", "모임 댓글 등록"),
                    ("gathering_update", "모임 정보 변경"),
                    ("gathering_cancel", "모임 취소"),
                    ("post_comment", "게시글 댓글 등록"),
                    ("comment_reply", "댓글 답글 등록"),
                    ("game_season_ending", "게임 시즌 종료 예정"),
                    ("game_season_reward", "게임 시즌 보상 지급"),
                    ("friend_request", "친구 요청"),
                    ("friend_accept", "친구 요청 수락"),
                    ("game_invite", "게임 초대"),
                    ("graduation_request", "졸업생 전환 신청"),
                    ("graduation_result", "졸업생 전환 결과"),
                ],
                max_length=20,
                verbose_name="알림 유형",
            ),
        ),
        migrations.CreateModel(
            name="GraduationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="신청 메모"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("rejected", "거절"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청일시"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리일시"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graduation_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "졸업생 전환 신청",
                "verbose_name_plural": "졸업생 전환 신청 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
