# Generated by Django 5.2.14 on 2026-10-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_graduate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="treats",
            field=models.PositiveIntegerField(default=0, verbose_name="사탕"),
        ),
        migrations.CreateModel(
            name="TreatTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="변동 수량")),
                (
                    "transaction_type",
                    models.CharField(max_length=30, verbose_name="유형"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="상세 내용"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="일시"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treat_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사탕 거래 내역",
                "verbose_name_plural": "사탕 거래 내역",
                "ordering": ["-created_at"],
            },
        ),
    ]
