# Generated by Django 5.2.14 on 2026-06-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotPlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateField(auto_now_add=True, verbose_name='플레이 일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='플레이 시간')),
                ('result_reward', models.PositiveIntegerField(default=0, verbose_name='획득 낙엽 수량')),
                ('result_grade', models.CharField(default='F', max_length=2, verbose_name='결과 등급')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_play_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '슬롯머신 플레이 로그',
                'verbose_name_plural': '슬롯머신 플레이 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
