# Generated by Django 5.2.14 on 2026-06-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_applegamescore"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="시즌 번호"),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="활성 시즌"
                    ),
                ),
                (
                    "rewards_distributed",
                    models.BooleanField(default=False, verbose_name="보상 지급 완료"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "게임 시즌",
                "verbose_name_plural": "게임 시즌 목록",
                "ordering": ["-number"],
            },
        ),
    ]
