# Generated by Django 5.2.14 on 2026-06-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_add_game_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameseason",
            name="warned_1d",
            field=models.BooleanField(default=False, verbose_name="1일 전 알림 전송"),
        ),
        migrations.AddField(
            model_name="gameseason",
            name="warned_3d",
            field=models.BooleanField(default=False, verbose_name="3일 전 알림 전송"),
        ),
    ]
