# Generated by Django 5.2.14 on 2026-06-30 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_add_warned_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_label",
                    models.CharField(max_length=50, verbose_name="시즌 표시명"),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="최종 순위")),
                ("reward", models.PositiveIntegerField(verbose_name="지급 낙엽 수량")),
                (
                    "shown",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="확인 여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_reward_claims",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시즌 보상 정산",
                "verbose_name_plural": "시즌 보상 정산 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
