# Generated by Django 5.2.14 on 2026-07-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_add_season_reward_claim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryMatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                (
                    "moves",
                    models.PositiveIntegerField(default=0, verbose_name="이동 횟수"),
                ),
                (
                    "time_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="소요 시간(초)"
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="플레이 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_match_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메모리 매칭 점수",
                "verbose_name_plural": "메모리 매칭 점수 목록",
                "ordering": ["-score", "played_at"],
            },
        ),
    ]
