# Generated by Django 5.2.14 on 2026-07-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_memorymatchscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memorymatchscore",
            options={
                "ordering": ["-score", "played_at"],
                "verbose_name": "카드 매칭 점수",
                "verbose_name_plural": "카드 매칭 점수 목록",
            },
        ),
        migrations.AddField(
            model_name="seasonrewardclaim",
            name="board",
            field=models.CharField(
                choices=[("apple_game", "마지막 잎새"), ("memory_match", "카드 매칭")],
                default="apple_game",
                max_length=20,
                verbose_name="게임 종류",
            ),
        ),
    ]
