# Generated by Django 5.2.14 on 2026-07-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_memorymatchscore_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonrewardclaim",
            name="board",
            field=models.CharField(
                choices=[
                    ("apple_game", "마지막 잎새"),
                    ("memory_match", "카드 매칭"),
                    ("number_speed", "넘버 스피드"),
                ],
                default="apple_game",
                max_length=20,
                verbose_name="게임 종류",
            ),
        ),
        migrations.CreateModel(
            name="NumberSpeedScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                (
                    "mistakes",
                    models.PositiveIntegerField(default=0, verbose_name="실수 횟수"),
                ),
                (
                    "time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="소요 시간(ms)"
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="플레이 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="number_speed_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "넘버 스피드 점수",
                "verbose_name_plural": "넘버 스피드 점수 목록",
                "ordering": ["-score", "played_at"],
            },
        ),
    ]
