# Generated by Django 5.2.14 on 2026-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_seasonrewardclaim_board_numberspeedscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonrewardclaim",
            name="board",
            field=models.CharField(
                choices=[
                    ("apple_game", "마지막 잎새"),
                    ("memory_match", "카드 매칭"),
                    ("number_speed", "넘버 스피드"),
                    ("pattern_recall", "패턴 리콜"),
                ],
                default="apple_game",
                max_length=20,
                verbose_name="게임 종류",
            ),
        ),
        migrations.CreateModel(
            name="PatternRecallScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="점수")),
                (
                    "level",
                    models.PositiveIntegerField(default=0, verbose_name="도달 레벨"),
                ),
                (
                    "played_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="플레이 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_recall_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "패턴 리콜 점수",
                "verbose_name_plural": "패턴 리콜 점수 목록",
                "ordering": ["-score", "played_at"],
            },
        ),
    ]
