# Generated by Django 5.2.14 on 2026-09-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_seasonrewardclaim_board_patternrecallscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PokerTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "대기 중"), ("playing", "진행 중")],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("preflop", "프리플랍"),
                            ("flop", "플랍"),
                            ("turn", "턴"),
                            ("river", "리버"),
                            ("showdown", "쇼다운"),
                        ],
                        default="preflop",
                        max_length=10,
                    ),
                ),
                (
                    "dealer_seat",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="딜러 버튼 자리"
                    ),
                ),
                (
                    "current_turn_seat",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="현재 차례 자리"
                    ),
                ),
                (
                    "turn_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="현재 차례 제한시각"
                    ),
                ),
                (
                    "next_hand_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 핸드 시작 예정시각"
                    ),
                ),
                ("pot", models.PositiveIntegerField(default=0, verbose_name="팟")),
                (
                    "current_bet",
                    models.PositiveIntegerField(
                        default=0, verbose_name="현재 스트리트 콜 금액"
                    ),
                ),
                (
                    "min_raise",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="최소 레이즈 단위"
                    ),
                ),
                (
                    "community_cards",
                    models.JSONField(
                        blank=True, default=list, verbose_name="커뮤니티 카드"
                    ),
                ),
                (
                    "deck",
                    models.JSONField(
                        blank=True, default=list, verbose_name="남은 덱 (서버 전용)"
                    ),
                ),
                (
                    "hand_number",
                    models.PositiveIntegerField(default=0, verbose_name="핸드 번호"),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="직전 핸드 결과 요약"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "포커 테이블",
                "verbose_name_plural": "포커 테이블",
            },
        ),
        migrations.CreateModel(
            name="PokerHandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hand_number", models.PositiveIntegerField()),
                ("pot", models.PositiveIntegerField()),
                ("community_cards", models.JSONField(blank=True, default=list)),
                ("winners", models.JSONField(blank=True, default=list)),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_logs",
                        to="game.pokertable",
                    ),
                ),
            ],
            options={
                "verbose_name": "포커 핸드 기록",
                "verbose_name_plural": "포커 핸드 기록 목록",
                "ordering": ["-ended_at"],
            },
        ),
        migrations.CreateModel(
            name="PokerSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveSmallIntegerField(verbose_name="자리 번호"),
                ),
                (
                    "stack",
                    models.PositiveIntegerField(default=0, verbose_name="보유 스택"),
                ),
                (
                    "current_bet",
                    models.PositiveIntegerField(
                        default=0, verbose_name="이번 스트리트 베팅액"
                    ),
                ),
                (
                    "contributed_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="이번 핸드 누적 베팅액"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "빈 자리"),
                            ("active", "참여 중"),
                            ("folded", "폴드"),
                            ("all_in", "올인"),
                            ("out", "이번 핸드 미참여"),
                        ],
                        default="empty",
                        max_length=10,
                    ),
                ),
                (
                    "hole_cards",
                    models.JSONField(blank=True, default=list, verbose_name="홀 카드"),
                ),
                ("has_acted_this_street", models.BooleanField(default=False)),
                (
                    "consecutive_timeouts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="연속 시간초과 횟수"
                    ),
                ),
                (
                    "leaving_after_hand",
                    models.BooleanField(
                        default=False, verbose_name="핸드 종료 후 퇴장 예정"
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poker_seats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="game.pokertable",
                    ),
                ),
            ],
            options={
                "verbose_name": "포커 좌석",
                "verbose_name_plural": "포커 좌석 목록",
                "ordering": ["seat_number"],
                "unique_together": {("table", "seat_number")},
            },
        ),
    ]
