# Generated by Django 5.2.14 on 2026-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_pokerchipwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokertable",
            name="min_raise",
            field=models.PositiveIntegerField(
                default=10000, verbose_name="최소 레이즈 단위"
            ),
        ),
    ]
