# Generated by Django 5.2.14 on 2026-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_alter_pokertable_min_raise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokertable",
            name="min_raise",
            field=models.PositiveIntegerField(
                default=5, verbose_name="최소 레이즈 단위"
            ),
        ),
    ]
