# Generated by Django 5.2.14 on 2026-09-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_alter_pokertable_min_raise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HighLowPlayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet", models.PositiveIntegerField(verbose_name="베팅 낙엽")),
                (
                    "streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="연속 성공 횟수"
                    ),
                ),
                (
                    "payout",
                    models.PositiveIntegerField(default=0, verbose_name="정산 낙엽"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("cashed_out", "캐시아웃"), ("busted", "실패")],
                        max_length=10,
                        verbose_name="결과",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="종료 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlow_play_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "하이로우 플레이 기록",
                "verbose_name_plural": "하이로우 플레이 기록 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HighLowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet", models.PositiveIntegerField(verbose_name="베팅 낙엽")),
                (
                    "current_rank",
                    models.PositiveSmallIntegerField(
                        verbose_name="현재 카드 랭크 (2~14, 11~14=J/Q/K/A)"
                    ),
                ),
                (
                    "streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="연속 성공 횟수"
                    ),
                ),
                (
                    "potential_payout",
                    models.PositiveIntegerField(
                        default=0, verbose_name="지금 캐시아웃 시 받을 낙엽"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlow_session",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "하이로우 진행 상태",
                "verbose_name_plural": "하이로우 진행 상태 목록",
            },
        ),
    ]
