# Generated by Django 5.2.14 on 2026-09-29 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_highlowplaylog_highlowsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GostopRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("matgo", "맞고 (2인)"), ("gostop", "고스톱 (3인)")],
                        default="matgo",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "대기 중"), ("playing", "진행 중")],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="판 진행 상태 (서버 전용)",
                    ),
                ),
                (
                    "turn_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="현재 차례 제한시각"
                    ),
                ),
                (
                    "next_game_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 판 시작 예정시각"
                    ),
                ),
                (
                    "carry_multiplier",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="나가리 누적 배수"
                    ),
                ),
                (
                    "next_first",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="다음 판 선 (좌석 번호)"
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="직전 판 결과 요약"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "고스톱 방",
                "verbose_name_plural": "고스톱 방 목록",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GostopGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.PositiveIntegerField(verbose_name="방 번호")),
                ("mode", models.CharField(default="matgo", max_length=10)),
                (
                    "chips",
                    models.PositiveIntegerField(
                        default=0, verbose_name="승자가 받은 칩"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="점수/지불 내역"
                    ),
                ),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gostop_wins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승자",
                    ),
                ),
            ],
            options={
                "verbose_name": "고스톱 판 기록",
                "verbose_name_plural": "고스톱 판 기록 목록",
                "ordering": ["-ended_at"],
            },
        ),
        migrations.CreateModel(
            name="GostopSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField(verbose_name="좌석 번호")),
                (
                    "stack",
                    models.PositiveIntegerField(default=0, verbose_name="보유 스택"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="game.gostoproom",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gostop_seat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "고스톱 좌석",
                "verbose_name_plural": "고스톱 좌석 목록",
                "ordering": ["room", "seat"],
                "unique_together": {("room", "seat")},
            },
        ),
    ]
