# Generated by Django 5.2.14 on 2026-09-29 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_highlowplaylog_highlowsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatgoGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.PositiveIntegerField(verbose_name="방 번호")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="최종 점수"),
                ),
                (
                    "chips",
                    models.PositiveIntegerField(default=0, verbose_name="이동한 칩"),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="점수 내역"
                    ),
                ),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matgo_losses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="패자",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matgo_wins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승자",
                    ),
                ),
            ],
            options={
                "verbose_name": "맞고 판 기록",
                "verbose_name_plural": "맞고 판 기록 목록",
                "ordering": ["-ended_at"],
            },
        ),
        migrations.CreateModel(
            name="MatgoRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host_stack",
                    models.PositiveIntegerField(default=0, verbose_name="방장 스택"),
                ),
                (
                    "guest_stack",
                    models.PositiveIntegerField(default=0, verbose_name="상대 스택"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "대기 중"), ("playing", "진행 중")],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="판 진행 상태 (서버 전용)",
                    ),
                ),
                (
                    "turn_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="현재 차례 제한시각"
                    ),
                ),
                (
                    "next_game_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 판 시작 예정시각"
                    ),
                ),
                (
                    "carry_multiplier",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="나가리 누적 배수"
                    ),
                ),
                (
                    "next_first",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="다음 판 선 (0=방장, 1=상대)"
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="직전 판 결과 요약"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matgo_guest_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상대",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matgo_host_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="방장",
                    ),
                ),
            ],
            options={
                "verbose_name": "맞고 방",
                "verbose_name_plural": "맞고 방 목록",
                "ordering": ["created_at"],
            },
        ),
    ]
