# Generated by Django 5.2.14 on 2026-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_gostop"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chips", models.BigIntegerField(default=0, verbose_name="하우스 칩")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "하우스 계좌",
                "verbose_name_plural": "하우스 계좌",
            },
        ),
    ]
