# Generated by Django 5.2.14 on 2026-10-01 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_housebank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YachtGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.PositiveIntegerField(verbose_name="방 번호")),
                ("pot", models.PositiveIntegerField(default=0, verbose_name="판돈")),
                (
                    "detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="점수/지급 내역"
                    ),
                ),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "요트 판 기록",
                "verbose_name_plural": "요트 판 기록 목록",
                "ordering": ["-ended_at"],
            },
        ),
        migrations.CreateModel(
            name="YachtRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="정원 (2~4)"
                    ),
                ),
                (
                    "stake",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="참가비(칩)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "대기 중"), ("playing", "진행 중")],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="판 진행 상태"
                    ),
                ),
                (
                    "pot",
                    models.PositiveIntegerField(default=0, verbose_name="이번 판 판돈"),
                ),
                (
                    "turn_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="현재 차례 제한시각"
                    ),
                ),
                (
                    "next_game_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 판 시작 예정시각"
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="직전 판 결과 요약"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "요트 방",
                "verbose_name_plural": "요트 방 목록",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="YachtSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField(verbose_name="좌석 번호")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="game.yachtroom",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yacht_seat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "요트 좌석",
                "verbose_name_plural": "요트 좌석 목록",
                "ordering": ["room", "seat"],
                "unique_together": {("room", "seat")},
            },
        ),
    ]
