# Generated by Django 5.2.14 on 2026-10-02 03:44

import django.db.models.deletion
from django.db import migrations, models


def close_single_poker_table(apps, schema_editor):
    """방 구조로 바뀌기 전의 단일 포커 테이블을 정리한다: 앉아 있던 칩(팟에 낸 칩 포함)을
    사람은 칩 지갑, AI는 하우스 계좌로 돌려주고 테이블을 지운다 (핸드 기록은 남는다)."""
    PokerTable = apps.get_model("game", "PokerTable")
    PokerSeat = apps.get_model("game", "PokerSeat")
    PokerChipWallet = apps.get_model("game", "PokerChipWallet")
    HouseBank = apps.get_model("game", "HouseBank")
    for seat in PokerSeat.objects.filter(user__isnull=False).select_related("user"):
        chips = seat.stack + seat.contributed_total
        if chips <= 0:
            continue
        if seat.user.is_bot:
            house, _ = HouseBank.objects.get_or_create(pk=1, defaults={"chips": 500 * 1000})
            house.chips += chips
            house.save(update_fields=["chips"])
        else:
            wallet, _ = PokerChipWallet.objects.get_or_create(user_id=seat.user_id)
            wallet.chips += chips
            wallet.save(update_fields=["chips"])
    PokerTable.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_yacht"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokertable",
            options={
                "ordering": ["created_at"],
                "verbose_name": "포커 방",
                "verbose_name_plural": "포커 방 목록",
            },
        ),
        migrations.AddField(
            model_name="gostoproom",
            name="tier",
            field=models.CharField(
                choices=[
                    ("beginner", "초보"),
                    ("intermediate", "중수"),
                    ("expert", "고수"),
                ],
                default="intermediate",
                max_length=12,
                verbose_name="단계",
            ),
        ),
        migrations.AddField(
            model_name="pokertable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pokertable",
            name="tier",
            field=models.CharField(
                choices=[
                    ("beginner", "초보"),
                    ("intermediate", "중수"),
                    ("expert", "고수"),
                ],
                default="intermediate",
                max_length=12,
                verbose_name="단계",
            ),
        ),
        migrations.AlterField(
            model_name="pokerhandlog",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hand_logs",
                to="game.pokertable",
            ),
        ),
        migrations.AlterField(
            model_name="pokertable",
            name="min_raise",
            field=models.PositiveIntegerField(
                default=0, verbose_name="최소 레이즈 단위"
            ),
        ),
        migrations.AddField(
            model_name="pokertable",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=5, verbose_name="좌석 수"),
        ),
        migrations.RunPython(close_single_poker_table, migrations.RunPython.noop),
    ]
