# Generated by Django 5.2.14 on 2026-10-08 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_game_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrickOrTreatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="모은 사탕"),
                ),
                (
                    "best",
                    models.PositiveIntegerField(default=0, verbose_name="최고 점수"),
                ),
                (
                    "earned",
                    models.PositiveIntegerField(default=0, verbose_name="보상 사탕"),
                ),
                (
                    "granted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="받은 사탕 (하루 상한 적용)"
                    ),
                ),
                (
                    "seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="걸린 시간(초)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="끝난 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trick_or_treat_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "트릭 오어 트릿 기록",
                "verbose_name_plural": "트릭 오어 트릿 기록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrickOrTreatRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.JSONField(
                        default=list, verbose_name="지도 (칸별 사탕, -1 = 귀신 집)"
                    ),
                ),
                (
                    "best",
                    models.PositiveIntegerField(
                        default=0, verbose_name="이 지도의 최고 점수"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trick_or_treat_run",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "트릭 오어 트릿 진행 중",
                "verbose_name_plural": "트릭 오어 트릿 진행 중",
            },
        ),
    ]
