# Generated by Django 5.2.14 on 2026-06-18 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=100, verbose_name='교수명')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='강의실')),
                ('day_of_week', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='테마 색상')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '시간표 과목',
                'verbose_name_plural': '시간표 과목 목록',
            },
        ),
    ]
