# Generated by Django 5.2.14 on 2026-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablesubject',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='테마 색상'),
        ),
    ]
